# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OwnLab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OwnLab

  pod 'Alamofire', '5.8.0'

  target 'OwnLabTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OwnLabUITests' do
    # Pods for testing
  end

end
